# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# B_IMS_FieldCalc_date_AMD01.py
# Created on: 2017-11-06 13:52:20.00000
# written for UNIFIL JGIS by Michael Iseli
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------




# Calculation of date and datepart related fields for monthly IMS incident analysis





# Import arcpy module
import arcpy


# Local variables:
SOIR_Analysis = "H:\\12e_Analysis\\Analysis.gdb\\SOIR_View\\SOIR_Analysis"
SOIR_150731__9_ = SOIR_Analysis
SOIR_150731__10_ = SOIR_150731__9_
SOIR_150731__8_ = SOIR_150731__10_
SOIR_150731__11_ = SOIR_150731__8_
SOIR_150731__3_ = SOIR_150731__11_
SOIR_150731__2_ = SOIR_150731__3_

# Process: Calculate Field_DayNum
arcpy.CalculateField_management(SOIR_Analysis, "DayNUM", "DatePart (\"d\",[Date])", "VB", "")

# Process: Calculate Field_MonthInc
arcpy.CalculateField_management(SOIR_150731__9_, "MonthInc", "DatePart (\"m\",[Date])", "VB", "")

# Process: Calculate Field_YearNum
arcpy.CalculateField_management(SOIR_150731__10_, "YearInc", "DatePart (\"yyyy\",[Date])", "VB", "")

# Process: Calculate Field_WkNum
arcpy.CalculateField_management(SOIR_150731__8_, "WeekNUM", "DatePart ( \"ww\", [Date] )", "VB", "")

# Process: Calculate Field_WeekDayNUM
arcpy.CalculateField_management(SOIR_150731__11_, "WeekDayNUM", "DatePart ( \"w\", [Date] )", "VB", "")

# Process: Calculate Field_yearcount
arcpy.CalculateField_management(SOIR_150731__3_, "yearcount", "[YearInc]-2010", "VB", "")


# return message that the code completed
print ("CALCULATION DATE AND DATEPART RELATED FIELDS COMPLETED")
