# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# D_IMS_FieldCalc_WeekNumYear.py
# Created on: 2017-11-06 15:06:55.00000
#   (generated by ArcGIS/ModelBuilder)
# written for UNIFIL JGIS by Michael Iseli
# Description:
# ---------------------------------------------------------------------------




# Import arcpy module
import arcpy



# code to calculate the field "week number in year" for IMS incident analysis

# Local variables:
SOIR_Analysis = "H:\\12e_Analysis\\Analysis.gdb\\SOIR_View\\SOIR_Analysis"
SOIR_Analysis__3_ = SOIR_Analysis

# Process: Calculate Field
arcpy.CalculateField_management(SOIR_Analysis, "WeekNUMyear", "([yearcount]*100)+ [WeekNUM]", "VB", "")

# return message that the code completed
print ("CALCULATION FIELD WEEK NUMBER WITHIN YEAR COMPLETED")
