# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# F_IMS_FieldCalc_Night.py
# Created on: 2017-11-09 09:03:43.00000
#   (generated by ArcGIS/ModelBuilder)
# written for UNIFIL JGIS by Michael Iseli
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Calculating field value for night/day time occurence of incidents


# Local variables:
SOIR_Analysis = "H:\\12e_Analysis\\Analysis.gdb\\SOIR_View\\SOIR_Analysis"
SOIR_Analysis_Layer = "SOIR_Analysis_Layer"
Seclection_DayTime = SOIR_Analysis_Layer
Calculated_DayTime = Seclection_DayTime
Selection_NightTime = Calculated_DayTime
LayerCalculatedNightTime = Selection_NightTime
SOIR_Analysis_Layer_2_ = LayerCalculatedNightTime

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(SOIR_Analysis, SOIR_Analysis_Layer, "", "", "OBJECTID_1 OBJECTID_1 VISIBLE NONE;Shape Shape VISIBLE NONE;OBJECTID OBJECTID VISIBLE NONE;incID incID VISIBLE NONE;Sector Sector VISIBLE NONE;Severity Severity VISIBLE NONE;Category Category VISIBLE NONE;Type Type VISIBLE NONE;TypeCode TypeCode VISIBLE NONE;ReportedBy ReportedBy VISIBLE NONE;Source Source VISIBLE NONE;Date Date VISIBLE NONE;Time Time VISIBLE NONE;Location Location VISIBLE NONE;UTM UTM VISIBLE NONE;QQQ QQQ VISIBLE NONE;Confirmati Confirmati VISIBLE NONE;FIR FIR VISIBLE NONE;StatusFIR StatusFIR VISIBLE NONE;SOI SOI VISIBLE NONE;StatusSOI StatusSOI VISIBLE NONE;DAIR DAIR VISIBLE NONE;StatusDAIR StatusDAIR VISIBLE NONE;EmailFromJ EmailFromJ VISIBLE NONE;FlagFromJO FlagFromJO VISIBLE NONE;EmailToJOC EmailToJOC VISIBLE NONE;FlagToJOC FlagToJOC VISIBLE NONE;StatusFina StatusFina VISIBLE NONE;Updated Updated VISIBLE NONE;Remark Remark VISIBLE NONE;created_us created_us VISIBLE NONE;created_da created_da VISIBLE NONE;last_edite last_edite VISIBLE NONE;last_edi_1 last_edi_1 VISIBLE NONE;SDE_STATE_ SDE_STATE_ VISIBLE NONE;DayNUM DayNUM VISIBLE NONE;MonthInc MonthInc VISIBLE NONE;YearInc YearInc VISIBLE NONE;MonthNum MonthNum VISIBLE NONE;MonthAge MonthAge VISIBLE NONE;WeekNUM WeekNUM VISIBLE NONE;BATT BATT VISIBLE NONE;WEIincS WEIincS VISIBLE NONE;WEIincA WEIincA VISIBLE NONE;incWEIGHT incWEIGHT VISIBLE NONE;RdType RdType VISIBLE NONE;InPosn InPosn VISIBLE NONE;InBuiltUp_A InBuiltUp_A VISIBLE NONE;NoPeople_Inc NoPeople_Inc VISIBLE NONE;WeekDayNUM WeekDayNUM VISIBLE NONE;Municipality Municipality VISIBLE NONE;Night Night VISIBLE NONE;IVO_BL IVO_BL VISIBLE NONE;WeightAge WeightAge VISIBLE NONE;THR_Relevance THR_Relevance VISIBLE NONE;TotalTHR_Weight TotalTHR_Weight VISIBLE NONE;GRID_ID GRID_ID VISIBLE NONE;WeekNUMyear WeekNUMyear VISIBLE NONE;MUN_OID MUN_OID VISIBLE NONE;yearcount yearcount VISIBLE NONE")

# Process: SelectRecords_DayTime
arcpy.SelectLayerByAttribute_management(SOIR_Analysis_Layer, "NEW_SELECTION", "Time > '0600' AND Time < '1901'")

# Process: Calculate_DayTime
arcpy.CalculateField_management(Seclection_DayTime, "Night", "0", "VB", "")

# Process: SwitchSelection_DayTime_NightTime
arcpy.SelectLayerByAttribute_management(Calculated_DayTime, "SWITCH_SELECTION", "")

# Process: Calculate_NightTime
arcpy.CalculateField_management(Selection_NightTime, "Night", "1", "VB", "")

# Process: ClearSelection
arcpy.SelectLayerByAttribute_management(LayerCalculatedNightTime, "CLEAR_SELECTION", "")




# return message that the code completed
print ("COMPLETED FIELD CALCULATION COMPLETED")
