# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# P_IMS_FieldCalc_Weight_incAssess.py
# Created on: 2018-02-01 21:18:34.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
SOIR_Analysis = "H:\\12e_Analysis\\Analysis.gdb\\SOIR_View\\SOIR_Analysis"
I_SOIR_Analysis_Confirmati = SOIR_Analysis
Value = "1"
Value__2_ = I_SOIR_Analysis_Confirmati
IncMunicipalityX = I_SOIR_Analysis_Confirmati

# Process: Iterate Feature Selection
arcpy.IterateFeatureSelection_mb(SOIR_Analysis, "Confirmati #", "false")

# Process: Get Field Value
arcpy.GetFieldValue_mb(I_SOIR_Analysis_Confirmati, "Confirmati", "String", "")

# Process: Calculate Field
arcpy.CalculateField_management(I_SOIR_Analysis_Confirmati, "WEIincA", "if Value (2) is \"Observed by UNIFIL\" = 1", "PYTHON", "")

