# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Q_IMS_FieldCalc_Weight_incSource.py
# Created on: 2018-02-01 21:20:47.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
SOIR_Analysis = "SOIR_Analysis"
SOIR_Analysis__11_ = SOIR_Analysis
SOIR_Analysis__15_ = SOIR_Analysis__11_
SOIR_Analysis__3_ = SOIR_Analysis__15_
SOIR_Analysis__4_ = SOIR_Analysis__3_
SOIR_Analysis__5_ = SOIR_Analysis__4_
SOIR_Analysis__6_ = SOIR_Analysis__5_
SOIR_Analysis__2_ = SOIR_Analysis__6_

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(SOIR_Analysis, "NEW_SELECTION", "Source = 'Alleged by IDF' OR Source = 'Alleged by LAF'")

# Process: Calculate Field
arcpy.CalculateField_management(SOIR_Analysis__11_, "WEIincS", "0.7", "VB", "")

# Process: Select Layer By Attribute (2)
arcpy.SelectLayerByAttribute_management(SOIR_Analysis__15_, "NEW_SELECTION", "Source = 'Observed by UNIFIL' OR Source = 'OGL'")

# Process: Calculate Field (2)
arcpy.CalculateField_management(SOIR_Analysis__3_, "WEIincS", "1.0", "VB", "")

# Process: Select Layer By Attribute (3)
arcpy.SelectLayerByAttribute_management(SOIR_Analysis__4_, "NEW_SELECTION", "Source = 'Other'")

# Process: Calculate Field (3)
arcpy.CalculateField_management(SOIR_Analysis__5_, "WEIincS", "0.5", "VB", "")

# Process: Select Layer By Attribute (4)
arcpy.SelectLayerByAttribute_management(SOIR_Analysis__6_, "CLEAR_SELECTION", "")

